### ISSUE TITLE
Why are there only span tags and nothing?

### ISSUE THREAD

**Issue by cowDungIsFlowers** [mlinquan/vue-awesome-countdown#2]
For example！

**Comment by mlinquan** [comment]
> For example！

说中文！

**Comment by cowDungIsFlowers** [comment]
这原来是中国人写的，厉害了。

**Comment by cowDungIsFlowers** [comment]
我使用你首页的例子；
<h1>倒计时：
  <countdown :left-time="101000"> 
    <span
      slot="process"
      slot-scope="{ timeObj }">
        {{ timeObj.ceil.s }}
      </span>
      <span slot="finish">干完!</span>
  </countdown>
</h1>
倒计时怎么显示不出来，span标签里面是空，我的vue版本是"vue": "^2.5.17"。

**Comment by mlinquan** [comment]
> 我使用你首页的例子；
> 
> # 倒计时： {{ timeObj.ceil.s }} 干完!
> 倒计时怎么显示不出来，span标签里面是空，我的vue版本是"vue": "^2.5.17"。

加我QQ 3554541，我给你看 注明vac
