### ISSUE TITLE
leftTime传入数值为毫秒还是秒？

### ISSUE THREAD

**Issue by chnshang** [mlinquan/vue-awesome-countdown#20]
项目里用的倒计时，后端返回的数值单位为秒，leftTime有时直接传入，有时需要乘以1000才显示正确。这是什么原因？

**Comment by mlinquan** [comment]
> 项目里用的倒计时，后端返回的数值单位为秒，leftTime有时直接传入，有时需要乘以1000才显示正确。这是什么原因？

毫秒
