### ISSUE TITLE
Update leftTime from method

### ISSUE THREAD

**Issue by DarkPreacher** [mlinquan/vue-awesome-countdown#21]
Is there any way I can do that?
Since that is a prop — I can't do it without getting `Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders` warning.
Tried to set it with `remainingTime` — no luck.

**Comment by mlinquan** [comment]
Do not try to modify any data inside the component. You can use props to modify the data or `$emit` to receive the corresponding data after the status changes.
