### ISSUE TITLE
Time zone setting

### ISSUE THREAD

**Issue by narduin** [mlinquan/vue-awesome-countdown#22]
Hello!
Is there a way to define on which time zone the countdown should be based ?
I currently have a countdown set to 6pm. The countdown sould show 20min left but on safari (iOS and mojave), it shows 2h20min…
I don't know if it is time zone related though.

Thanks a lot!

**Comment by mlinquan** [comment]
> Hello!
> Is there a way to define on which time zone the countdown should be based ?
> I currently have a countdown set to 6pm. The countdown sould show 20min left but on safari (iOS and mojave), it shows 2h20min…
> I don't know if it is time zone related though.
> 
> Thanks a lot!

Your source code please.

**Comment by narduin** [comment]
```vue
<no-ssr>
    <vac :end-time="new Date('2019-08-29T18:00:00')">
        <span slot="process" slot-scope="{ timeObj }">
            {{ `${timeObj.d}:${timeObj.h}:${timeObj.m}:${timeObj.s}` }}
        </span>
        <span slot="finish">Done!</span>
    </vac>
</no-ssr>
```
I'm using Nuxt js.
I cannot disclose all the source code right now. Do you need more ?

**Comment by mlinquan** [comment]
> ```
> <no-ssr>
>     <vac :end-time="new Date('2019-08-29T18:00:00')">
>         <span slot="process" slot-scope="{ timeObj }">
>             {{ `${timeObj.d}:${timeObj.h}:${timeObj.m}:${timeObj.s}` }}
>         </span>
>         <span slot="finish">Done!</span>
>     </vac>
> </no-ssr>
> ```
> 
> I'm using Nuxt js.
> I cannot disclose all the source code right now. Do you need more ?

New Data defaults to local time zone
Optional
New Date ('2019/08/29 18:00:00 GMT+0600')
This format

**Comment by narduin** [comment]
Works great thank you!
