### ISSUE TITLE
How can use vue-awesome-countdown with typescript ?

### ISSUE THREAD

**Issue by abdallahn** [mlinquan/vue-awesome-countdown#23]
I try to use the vue-awesome-countdown at my project this is my step
1- npm install vue-awesome-countdown --save
2- npm install
3- import the  vue-awesome-countdown 
import vueAwesomeCountdown from "vue-awesome-countdown";
![image](https://user-images.githubusercontent.com/39025280/66753418-0fd99900-ee94-11e9-980c-526350a1f4f4.png)

**Comment by lle66** [comment]
try to install again

**Comment by pabo99** [comment]
I'm trying to install it with `yarn`, but I got the same error
