### ISSUE TITLE
switchCountdown not really stopping the timer 

### ISSUE THREAD

**Issue by yaki6** [mlinquan/vue-awesome-countdown#41]
as the example is showing 
https://vac.js.org/examples/methods/switch-countdown.html

When I call the switchCountdown(), the timer seems to stop, but the time is still lapsing. When I call the method again, the timer starts not from where I stopped but jumps right to how long has lapsed.

Is this behavior intended or is it a bug?

**Comment by mlinquan** [comment]
> as the example is showing
> https://vac.js.org/examples/methods/switch-countdown.html
> 
> When I call the switchCountdown(), the timer seems to stop, but the time is still lapsing. When I call the method again, the timer starts not from where I stopped but jumps right to how long has lapsed.
> 
> Is this behavior intended or is it a bug?

You can try 
``` js
vac.pauseCountdown()
```

**Comment by Yaki666** [comment]
> > as the example is showing
> > https://vac.js.org/examples/methods/switch-countdown.html
> > When I call the switchCountdown(), the timer seems to stop, but the time is still lapsing. When I call the method again, the timer starts not from where I stopped but jumps right to how long has lapsed.
> > Is this behavior intended or is it a bug?
> 
> You can try
> 
> ```js
> vac.pauseCountdown()
> ```

Thank you. More discussion of the behavior. What is the intention of designing the function of a switch that does not stop the timer actually, but just show it is stopped?

**Comment by mlinquan** [comment]
The end time of the countdown does not change because you stop the countdown, so there will be a time jump when you restart the countdown, and the remaining time will be recalculated when the countdown is suspended and started again. This is the difference between the two.
