### ISSUE TITLE
Start event not called with autoStart false

### ISSUE THREAD

**Issue by adrlen** [mlinquan/vue-awesome-countdown#44]
Hello, great library !

Start event doesn't seem to be called when `autoStart` is set to false and starting countdown with `startCountdown` method.

Thanks

**Comment by mlinquan** [comment]
Next Monday I will take time to focus on your problem and solve it. Thank you for your support!

**Comment by mlinquan** [comment]
This problem has been fixed in vue-awesome-countdown@1.1.3 version.
Thanks again!
