### ISSUE TITLE
Is it possible to count up?

### ISSUE THREAD

**Issue by alexwohlbruck** [mlinquan/vue-awesome-countdown#62]
I would like to implement a type of timer that counts the amount of time since a given timestamp. I am already using this library for a countdown so I'd prefer to keep it all the same.

I've tried:

```html
<countdown start-time="2022-01-07T00:00:00Z">
    <template v-slot:process="props">
          <!-- This never shows -->
    </template>
</countdown>
```

This doesn't seem to work, but I was wondering if there is any way to do it with this library.

**Comment by mlinquan** [comment]
> I would like to implement a type of timer that counts the amount of time since a given timestamp. I am already using this library for a countdown so I'd prefer to keep it all the same.
> 
> I've tried:
> 
> ```
> <countdown start-time="2022-01-07T00:00:00Z">
>     <template v-slot:process="props">
>           
>     </template>
> </countdown>
> ```
> 
> This doesn't seem to work, but I was wondering if there is any way to do it with this library.

The `end-time` or `left-time` is required.

**Comment by alexwohlbruck** [comment]
Looks like that isn't a feature of the library. I've implemented my own timer now, but thanks!
