### ISSUE TITLE
beforeStart slot be preheat

### ISSUE THREAD

**Issue by ZhangBohan** [mlinquan/vue-awesome-countdown#7]
I read the source code and real state, can't find `before` state set, should the `README.md` doc update the `before` slot to `preheat` or change the source code?

**Comment by mlinquan** [comment]
`before` slot的的话  只有`autoStart`为`false`时才能看到效果，因为默认是自动开始倒计时。
`preheat` slot的话，代码里有更新，但是文档里没有更新，`preheat` slot只有开始时间也就是`startTime`为未来时间的时候才有效。
例子在这->https://vac.js.org/examples/event-start-time.html
不知道我的回答是不是回答道点上了。
有其他问题可以随时联系我QQ：3554541(同微信)，
也欢迎pr，谢谢！
